# Generated by Django 6.0.7 on 2026-07-09 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0002_category_prompt_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='prompts.prompt')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prompts.category')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='prompts.prompt')),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
    ]
