# Generated by Django 6.0.7 on 2026-07-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0004_prompt_is_public_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prompt',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
