# Generated by Django 6.0.7 on 2026-07-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0005_prompt_is_archived_prompt_is_pinned'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#6c757d', max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='prompt',
            name='ai_model',
            field=models.CharField(blank=True, choices=[('', 'Not specified'), ('claude', 'Claude'), ('chatgpt', 'ChatGPT'), ('gemini', 'Gemini'), ('other', 'Other / Local')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='prompt',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prompt',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='prompts', to='prompts.tag'),
        ),
    ]
