# Generated by Django 6.0.7 on 2026-07-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0006_tag_prompt_ai_model_prompt_rating_prompt_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='share',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
    ]
